### ISSUE TITLE
Centrer du texte

### ISSUE THREAD

**Issue by Sylvain2703** [sfeir-open-source/sfeir-school-template#14]
Lorsque l'on utilise la classe CSS `center`, le texte n'est pas centré.

Par exemple, dans [docs/markdown/00-school/00-TITLE.md](https://github.com/sfeir-open-source/sfeir-school-template/blob/master/docs/markdown/00-school/00-TITLE.md) le centrage de la balise paragraphe et le commentaire `<!-- .element: class="center" -->` ne sont pris en compte.

Pour corriger ce souci, on peut appliquer `text-align: center` dans [src/scss/utils/helper.scss](https://github.com/sfeir-open-source/sfeir-school-theme/blob/master/src/scss/utils/helper.scss) mais cela semble concerner les images seulement.

**Comment by jefBinomed** [comment]
pas dans le bon repo cf school theme
